### PR TITLE
add debug-version suffix for both version and id

### PR DESCRIPTION
**Pull request by z3ntu**

### CODE REVIEW

**Comment by M1cha** [comment]
a suffix with a leading dash? I didn't test this commit but it sounds weird.

**Comment by z3ntu** [comment]
screenshot_2016-11-03-07-42-53

**Comment by M1cha** [comment]
sry I shouldn't think about english vocables at 6am :D I confused prefix with suffix.
LGTM

**Comment by z3ntu** [comment]
;)

**Comment by M1cha** [comment]
if you rebase this I'll merge

**Comment by z3ntu** [comment]
Rebased.

**Pull request merged**
