### PR TITLE
Update gitignore and remove newly ignored files

### PR DESCRIPTION
**Pull request by z3ntu**
If you want to provide a binary on github, you should use the "Releases" on github.

### CODE REVIEW

**Comment by M1cha** [comment]
I'll rebase the repo to remove the apk which I accidentally committed to make the repo 2mb smaller.
can you explain all the gitignore changes? they do some weird things like replacing /.idea with .idea/

**Comment by z3ntu** [comment]
The `.idea/` ignores all folders called `.idea` no matter where they are located. And it's basically the content of https://github.com/github/gitignore/blob/master/Android.gitignore but you can take exactly that if you want. (it doesn't ignore the `.idea` folder itself, just some files in there.

**Comment by M1cha** [comment]
can you rebase this?

**Comment by z3ntu** [comment]
Do you really want to remove the whole `.idea` directory. According to the "official" `.gitignore` only 

```
# Intellij
*.iml
.idea/workspace.xml
.idea/libraries
```

should not be included to make the project easily be openable on new clones.

**Comment by M1cha** [comment]
yes I'm sure because these files hold way too much information like the name of the directory the files are in. That obviously causes loading errors.

Also if you look at any official Google app/sample then you can see that they always exclude the whole .idea directory.

**Comment by z3ntu** [comment]
I checked again and the files which do not get ignored do not contain any reference to the location (just the variable `$PROJECT_DIR$`)

**Comment by M1cha** [comment]
well I'm not sure if I did anything wrong or they fixed a few things, but I had probems with that in past.
But does it actually make any difference if we ignore /.idea or not? afaik the lack of this directory only causes AS to show a message once when opening the project for the first time.

**Comment by z3ntu** [comment]
Mostly you have problems (when the directory is absent) in more complicated projects with multiple modules (which this project doesn't have). But I think the inclusion of these files only help people get started quicker (as 1. Android Studio recognized that this directory is an existing project and 2. There are no problems opening this when the project gets more complicated).

**Comment by M1cha** [comment]
I researched a little bit about this topic and it seems that it shouldn't make any difference because all the project specific configuration like compiler settings are configured using gradle, not using IDEA.

So, which problems do you think there would be with bigger projects?(there shouldn't be any)
Also, we already do have two subprojects.

**Pull request closed without merging**
